### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [leoschuler/gtag-consent-management#1]
https://github.com/leoschuler/gtag-consent-management/blob/eb710cb9146b3a0b483bf41b951f8ca157ea4263/template.tpl#L619

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

Thanks!

**Comment by leoschuler** [comment]
fix it, while changing / testing the tag, I imported again, and I notice that if I change the id of the tag (from "cvt_temp_public_id" to another id) the tag stop working, so I rename it to cvt_temp_public_id. @philpott, will this id be changed once published?
